// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class linkuptablesdataanotationaddedtothecustomertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linkuptablesdataanotationaddedtothecustomertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201811151539418_linkup tables,data anotation added to the customer table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
